name: Server CD

on:
  push:
    branches: [master]

jobs:
  build_image_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Automated Version Bump
        uses: ./.github/actions/gh-action-bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
          GITHUB_EMAIL: barclaysd@me.com
      - name: 'Get latest tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
